# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "ubuntu" ]
  pull_request:
    branches: [ "main", "ubuntu" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      minio:
        image: quay.io/minio/minio:latest
        options: >-
          --name minio
          -p 9000:9000
          -e AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
          -e AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
          quay.io/minio/minio server /data
        ports:
          - 9000:9000  # MinIO API port

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
