name: Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
       packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x' 

    - name: Build and pack
      run: dotnet pack --configuration Release 
      
    - name: Add Source
      run: |
         dotnet nuget add source --username USACE --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/USACE/index.json"
     
    - name: Publish nuget package
      run: dotnet nuget push "./Usace.CC.Plugin/bin/Release/*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
 
